// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZgMGPvtFbTFJMHrFmYd9GySxBMp0lTgU',
    appId: '1:487052916765:web:1c52c007db48ff144caef4',
    messagingSenderId: '487052916765',
    projectId: 'task-31169',
    authDomain: 'task-31169.firebaseapp.com',
    storageBucket: 'task-31169.appspot.com',
    measurementId: 'G-XCY6ZK7RNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDycjyNH5uPLFljgZQi6vNsKF4wNse-niE',
    appId: '1:487052916765:android:5704d3f0f35e70f24caef4',
    messagingSenderId: '487052916765',
    projectId: 'task-31169',
    storageBucket: 'task-31169.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeKNKg4Autk-st9wgyupyHBLc3oSxZteU',
    appId: '1:487052916765:ios:27ad3f89a6c985b74caef4',
    messagingSenderId: '487052916765',
    projectId: 'task-31169',
    storageBucket: 'task-31169.appspot.com',
    iosClientId: '487052916765-l64tteud283idm0n0fa1pjnqj2via2gh.apps.googleusercontent.com',
    iosBundleId: 'com.example.task',
  );
}
